[package]
name = "war3parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
image = "0.24.3"
image-blp = "1.2.0"
mpq = "0.8.0"
nom = "7.1.3"
