[package]
name = "war3parser-wasm"
version = { workspace = true }
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
war3parser = { path = "../war3parser" }
